### ISSUE TITLE
List of Fixes for 05/04

### ISSUE THREAD

**Issue by elliesch** [hover2pi/SEDkit#10]
I will populate this list early next week!

**Comment by elliesch** [comment]
- Add 3D inference for asymmetric uncertainties on distances
- Add MakeSED capabilities when no spectra are available
   - One that works with photometry only
   - One that estimates spectral type from SED shape
- Add method to save outputs and plots on large batches of stars

**Comment by ECGonzales** [comment]
Determine why sometimes spectra are not displayed or useable in their format.
Fix issues with spectra scaling when there is photometry for some objects.

**Comment by hover2pi** [comment]
No asymmetric uncertainties yet, but that is a separate issue. Everything else has been added.
