### ISSUE TITLE
Weight for scaling spectra to photometry correct?

### ISSUE THREAD

**Issue by ECGonzales** [hover2pi/sedkit#39]
Check to see if the way the spectrum is scaled to the photometry with the weight using the chi-square minimization from Cushing 2008 is the best way to scale.

**Comment by hover2pi** [comment]
@ECGonzales Is there a specific problem you identified with the Cushing08 method? Or did you have an alternate scaling formula you would recommend? I'd be happy to implement it, perhaps making the scaling method an option for the user.

I'm going to close this issue for now as it's too vague for me to act on. Feel free to open a new issue is there is a specific improvement or problem you find. Thanks!
