### ISSUE TITLE
Spectra not plotting for source id 1304

### ISSUE THREAD

**Issue by ECGonzales** [hover2pi/SEDkit#5]
![problem1304](https://cloud.githubusercontent.com/assets/17441465/23175840/aa0c2786-f82e-11e6-9125-a00b216802ff.png)
Spectra not plotting correctly. Could the conversion from Jy to erg/s/cm2/A be not functioning properly?

**Comment by hover2pi** [comment]
Should be fixed in the rewrite. Can you post a snippet so I can try to reproduce the issue?

**Comment by ECGonzales** [comment]
a= SEDs.MakeSED(1304, db, spec_ids=[3175,3061,1668], age=(5000,10000), est_mags=False, evo_model='nc-03_age', pi=(40.2369,0.6389))

I'm not sure if you have the latest version of the database, but you should have spec id 1668, which is the problematic one.

**Comment by ECGonzales** [comment]
So this source has two MIR spectra and 1668 gives this problem, but 3076 doesn't.
