### ISSUE TITLE
Fitting unresolved binaries?

### ISSUE THREAD

**Issue by ericagol** [hover2pi/sedkit#55]
Hi @hover2pi -

I am wondering whether sedkit has the capability of fitting unresolved binaries?

The application I'm thinking of is fitting for temperature inhomogeneity on
TRAPPIST-1 by modeling it as two(+) stars with different temperatures.  Is this
something sedkit might be capable of, or that could be added easily?

Thanks,

Eric Agol

**Comment by hover2pi** [comment]
Eric,

No, it can’t do that yet but Adam Burgasser has the Splat package that does exactly that! It’s at github.com/aburgasser/splat. It’s a little harder to use than sedkit (in my opinion) but has the capability you’re looking for. This is on my to do list. If you want to make a Github issue for sedkit, feel free!

But what you’re describing is basically what we did in Wakeford et al. (2018) to determine parameters for Trappist-1g. Check it out!

- Joe

On Sep 15, 2020, at 12:55 PM, Eric Agol <notifications@github.com> wrote:

﻿

Hi @hover2pi<https://github.com/hover2pi> -

I am wondering whether sedkit has the capability of fitting unresolved binaries?

The application I'm thinking of is fitting for temperature inhomogeneity on
TRAPPIST-1 by modeling it as two(+) stars with different temperatures. Is this
something sedkit might be capable of, or that could be added easily?

Thanks,

Eric Agol

**Comment by ericagol** [comment]
@hover2pi  Thanks for your quick help!  I'm familiar with the Wakeford et al. (2018) paper, and I'm interested in carrying this out for all seven planets based on the data from Ducrot et al. (2020).  Take care, Eric
