### ISSUE TITLE
Updating numpy/astropy breaks SEDkit

### ISSUE THREAD

**Issue by ECGonzales** [hover2pi/SEDkit#6]
Not sure which package did it. I had numpy==1.12.0 and astropy=1.3 and SEDkit was taking about 10 minutes to generate an SED. Downgraded to numpy=1.11.1 and astropy=1.2.1 and time to generate SED is normal (less than 1 minute).

**Comment by dr-rodriguez** [comment]
Can confirm this happens to me as well (updating astrodbkit updates astropy which in turn updates numpy), but not sure what part of the SEDkit code is part of the slow-down.

**Comment by hover2pi** [comment]
Fixed in the rewrite.
