### ISSUE TITLE
Please add data/models acknowledgements

### ISSUE THREAD

**Issue by aburgasser** [hover2pi/sedkit#62]
Hi Joe, I'm hoping to make use of SEDkit for our spectral analysis, but can I ask before you go much further to make sure there are proper citations and acknowledgements for the models and data you're posting here. For the spex prism libraries, the paper and acknowledgement is given at http://pono.ucsd.edu/~adam/browndwarfs/spexprism/:

_The paper to cite for SPL and SPLAT is
Burgasser A. J. 2014 in International Workshop on Stellar Spectral Libraries, ASI Conference Series 11, ed. H. P. Singh, P. Prugniel and I. Vauglin (Bangalore: Astronomical Society of India), pp. 7-16

For tracking purposes, please consider including the following in the acknowledgments of your publication or presentation:

"This research has benefitted from the SpeX Prism Library (and/or SpeX Prism Library Analysis Toolkit), maintained by Adam Burgasser at http://www.browndwarfs.org/spexprism"_

More importantly, it is important that the individual spectral data citations (e.g., bibcodes) are present. These may or may not be in the fits files; if you need help with this I'm happy to do so.

**Comment by hover2pi** [comment]
Hi @aburgasser ! Yes, I will be tracking references for all data and generating bibtex entries for each that a user can export. I'll tag and close this issue once the feature is implemented. I'm releasing v1.1.1 imminently and submitting the software paper this week!

**Comment by hover2pi** [comment]
This is live in #83 . The paper references for all data can be found in the `refs` attribute of any `SED` object.
