### ISSUE TITLE
Please upgrade PyPI version to use astropy 4.3.1

### ISSUE THREAD

**Issue by sundarjhu** [hover2pi/sedkit#72]
Hi, would you be able to upgrade the PyPI version of sedkit to become identical with the source in the repository?

A pip install results in astropy problems.

Thanks!

**Comment by hover2pi** [comment]
Yes! I'm about to release v1.2 with the `astropy` upgrade, which fixes those install issues. Thanks for your patience!

**Comment by hover2pi** [comment]
v1.2.1 released with #70 .
