### ISSUE TITLE
Same Radius

### ISSUE THREAD

**Issue by graceparkk** [hover2pi/sedkit#77]
HI! I've been running various objects with the SEDkit and found out that it gives out the same radius for all objects; regardless of the object, it gives out 0.9731158731046832 jupiterRad.

**Comment by hover2pi** [comment]
Ok I'll take a look! Thanks for letting me know.

**Comment by SherelynA** [comment]
Hello! @hover2pi  I just wanted to add more info to this error that we are getting. The line of code we get when initializing the sed in particular for the radius says  `Setting radius to (<Quantity 0.97311587 jupiterRad>, <Quantity 0. jupiterRad>, <Quantity 0. jupiterRad>) with reference '2013ApJS..208....9P`. Overall, is the radius of the objects being inferred using a specific method?

**Comment by hover2pi** [comment]
Ok, the fix for this is in the next release #80

**Comment by SherelynA** [comment]
thanks, super excited for the new release!
