### ISSUE TITLE
Scaling the Spectrum 

### ISSUE THREAD

**Issue by graceparkk** [hover2pi/sedkit#79]
Hello! While I was plotting the SEDs, I realized that the spectrum was scaling differently with and without photometry points. I was wondering about the mechanism that was used to scale the spectrum. 

Also, the following image is a comparison between the plot that I got and the plot from Brewster. The orange line (SED that I created) should line up with the green line, but I have no idea why it doesn't align with it in the mir spectra. 
![image](https://user-images.githubusercontent.com/108310946/187009026-329b3c23-802c-4405-b529-72518c1e1860.png)

I've tried adding and dropping WISE photometry points, but the SED still doesn't match up.  

<img width="981" alt="Screen Shot 2022-08-26 at 3 21 33 PM" src="https://user-images.githubusercontent.com/108310946/186977096-da3b7500-4a7c-425f-97a7-957c40a531b8.png">
<img width="932" alt="Screen Shot 2022-08-26 at 3 20 33 PM" src="https://user-images.githubusercontent.com/108310946/186977103-ff196054-c906-4c60-a67c-5bacec6b905f.png">

Is there a reason why the mir spectra is being plotted in this way? 

Thanks.

**Comment by hover2pi** [comment]
Hi @graceparkk ! I'll take a look at this next week but I'm not too sure as of yet what the issue is.
