### ISSUE TITLE
SEDkit rewrite not processing dictionary on initial input

### ISSUE THREAD

**Issue by elliesch** [hover2pi/SEDkit#9]
I am trying to run SEDkit using photometry only, but I am getting a `Nonetype` error.

I have tried running the code in two ways:

1. `a = sed.MakeSED(225, db)`
2. 
```python
a_dict = {'photometry':'*', 'parallaxes':4}
a = sed.MakeSED(225, db, from_dict=a_dict)
```

Both methods give me the same error:
```python
/Users/elliannaschwab/codes/SEDkit/SEDkit/sed.py in __init__(self, source_id, db, from_dict, wave_units, flux_units, SED_trim, SED_split, name, verbose, **kwargs)
    225                 dummy = db.query(qry, fmt='table')
    226                 print(dummy)
--> 227                 dummy.remove_row(0)
    228                 setattr(self, table, at.QTable(dummy))
    229 

AttributeError: 'NoneType' object has no attribute 'remove_row'
```

I added a print statement to see dummy, but it is empty and prints out as `None`

**Comment by hover2pi** [comment]
Ooooh, I know what this is. This was a terrible hack I added for tables that had no data. The problem with SQLite is that is returns None if a query has no results rather than an empty table. I'll fix it.


Joe Filippazzo, Ph.D.
Senior Research and Instrument Analyst
Space Telescope Science Institute
(410) 338-6871

________________________________

**Comment by elliesch** [comment]
@hover2pi just checking in on this. How is the fix going?

**Comment by hover2pi** [comment]
Ok, this is changed in the master branch. Now you can make an SED by just specifying the database object and the `id` from each table.

```from SEDkit.sed import SED
from astrodbkit import astrodb
db = astrodb.Database('$BDNYCdb/bdnycdev.db')
s = SED()
s.from_database(db, photometry=[1,2,3,4], parallax=23, spectral_type=2, spectra=[2], source_id=2)
s.results```
